class Loc {
  static String lang = 'ru';

  static String t(String key) => (lang == 'en' ? _en : _ru)[key] ?? key;
  static String mode(String value) => t('mode_$value');

  static const Map<String, String> _ru = {
    'navHome': 'Главная',
    'navSettings': 'Настройки',
    'configuration': 'Конфигурация',
    'tooltipIpset': 'Обновить IPSet-список',
    'noConfigsPath': 'Конфиги не найдены — укажи путь в настройках',
    'noConfigs': 'Конфиги не найдены',
    'start': 'Запустить',
    'stop': 'Остановить',
    'restart': 'Перезапустить',
    'gameFilter': 'Игровой фильтр',
    'ipsetFilter': 'IPSet-фильтр',
    'darkTheme': 'Тёмная тема',
    'launchWindows': 'Запускать вместе с Windows',
    'zapretAutostart': 'Автозапуск Zapret',
    'language': 'Язык',
    'zapretUpdates': 'Обновления Zapret',
    'appUpdates': 'Обновления приложения',
    'pathToZapret': 'Путь к Zapret',
    'github': 'GitHub · Zapret',
    'pathUpdated': 'Путь обновлён',
    'msgBusy': 'Уже выполняется…',
    'msgLaunch': 'Запуск',
    'msgStop': 'Остановка: winws.exe завершён',
    'msgAutostartSet': 'Автозапуск установлен',
    'msgAutostartRemoved': 'Автозапуск удалён',
    'msgNoConfigs': 'Нет конфигов для автозапуска',
    'msgIpsetUpdated': 'IPSet: список обновлён',
    'msgIpsetHttp': 'IPSet: ошибка HTTP',
    'msgIpsetError': 'IPSet: ошибка',
    'msgAlready': 'уже в режиме',
    'msgUnknown': 'неизвестный режим',
    'msgApplies': 'применится после перезапуска zapret',
    'msgLatestZ2': 'Последняя версия Z2',
    'msgHttp': 'Ошибка HTTP',
    'msgError': 'Ошибка',
    'msgNoZip': 'В релизе нет .zip',
    'msgUnpack': 'Ошибка распаковки',
    'msgSearch': 'Поиск релиза…',
    'msgDownloading': 'Скачивание',
    'msgInstalling': 'Установка…',
    'msgInstalled': 'скачан и установлен',
    'msgDownloadError': 'Ошибка скачивания',
    'msgEmpty': 'пустой ответ сервера',
    'msgExtracting': 'Распаковка…',
    'otaLatest': 'Уже установлена последняя версия',
    'otaRestart': 'Перезапуск…',
    'updateAvailable': 'Доступна новая версия',
    'installUpdate': 'Установить',
    'cancel': 'Отмена',
    'currentVersion': 'Текущая версия',
    'installingUpdate': 'Установка обновления…',
    'mode_disabled': 'отключён',
    'mode_all': 'TCP + UDP',
    'mode_tcp': 'TCP',
    'mode_udp': 'UDP',
    'mode_loaded': 'Загружен',
    'mode_none': 'Нет',
    'mode_any': 'Любой',
    'downloadZapret': 'Скачать Zapret',
    'removeService': 'Удалить сервис',
    'removeServiceTitle': 'Удалить сервис zapret?',
    'removeServiceBody':
        'Обход будет остановлен, службы zapret и WinDivert будут удалены.',
    'remove': 'Удалить',
    'msgServiceRemoved': 'Сервис zapret удалён',
    'footer': 'сделано с ♥ для свободного интернета',
  };

  static const Map<String, String> _en = {
    'navHome': 'Home',
    'navSettings': 'Settings',
    'configuration': 'Configuration',
    'tooltipIpset': 'Update IPSet list',
    'noConfigsPath': 'No configs found — set the path in settings',
    'noConfigs': 'No configs found',
    'start': 'Start',
    'stop': 'Stop',
    'restart': 'Restart',
    'gameFilter': 'Game Filter',
    'ipsetFilter': 'IPSet Filter',
    'darkTheme': 'Dark theme',
    'launchWindows': 'Launch with Windows',
    'zapretAutostart': 'Zapret autostart',
    'language': 'Language',
    'zapretUpdates': 'Zapret updates',
    'appUpdates': 'App updates',
    'pathToZapret': 'Path to Zapret',
    'github': 'GitHub · Zapret',
    'pathUpdated': 'Path updated',
    'msgBusy': 'Already running…',
    'msgLaunch': 'Launch',
    'msgStop': 'Stop: winws.exe terminated',
    'msgAutostartSet': 'Autostart installed',
    'msgAutostartRemoved': 'Autostart removed',
    'msgNoConfigs': 'No configs for autostart',
    'msgIpsetUpdated': 'IPSet: list updated',
    'msgIpsetHttp': 'IPSet: HTTP error',
    'msgIpsetError': 'IPSet: error',
    'msgAlready': 'already in mode',
    'msgUnknown': 'unknown mode',
    'msgApplies': 'applies after zapret restart',
    'msgLatestZ2': 'Latest Z2 version',
    'msgHttp': 'HTTP error',
    'msgError': 'Error',
    'msgNoZip': 'No .zip in release',
    'msgUnpack': 'Unpack error',
    'msgSearch': 'Searching release…',
    'msgDownloading': 'Downloading',
    'msgInstalling': 'Installing…',
    'msgInstalled': 'downloaded and installed',
    'msgDownloadError': 'Download error',
    'msgEmpty': 'empty server response',
    'msgExtracting': 'Extracting…',
    'otaLatest': 'Already up to date',
    'otaRestart': 'Restarting…',
    'updateAvailable': 'New version available',
    'installUpdate': 'Install',
    'cancel': 'Cancel',
    'currentVersion': 'Current version',
    'installingUpdate': 'Installing update…',
    'mode_disabled': 'disabled',
    'mode_all': 'TCP + UDP',
    'mode_tcp': 'TCP',
    'mode_udp': 'UDP',
    'mode_loaded': 'Loaded',
    'mode_none': 'None',
    'mode_any': 'Any',
    'downloadZapret': 'Download Zapret',
    'removeService': 'Remove service',
    'removeServiceTitle': 'Remove zapret service?',
    'removeServiceBody':
        'The bypass will be stopped and the zapret / WinDivert services will be removed.',
    'remove': 'Remove',
    'msgServiceRemoved': 'Zapret service removed',
    'footer': 'made with ♥ for free internet',
  };
}