class Loc {
  static String lang = 'ru';
  static Map<String, String> get _map =>
      lang == 'en' ? _en : lang == 'es' ? _es : lang == 'de' ? _de : _ru;
  static String t(String key) => _map[key] ?? key;
  static String mode(String value) => t('mode_$value');

  static const Map<String, String> _ru = {
    'navHome': 'Главная',
    'navSettings': 'Настройки',
    'configuration': 'Конфигурация',
    'tooltipIpset': 'Обновить IPSet-список',
    'noConfigsPath': 'Конфиги не найдены — укажи путь в настройках',
    'noConfigs': 'Конфиги не найдены',
    'start': 'Запустить',
    'stop': 'Остановить',
    'restart': 'Перезапустить',
    'gameFilter': 'Игровой фильтр',
    'ipsetFilter': 'IPSet-фильтр',
    'darkTheme': 'Тёмная тема',
    'launchWindows': 'Запускать вместе с Windows',
    'zapretAutostart': 'Автозапуск Zapret',
    'language': 'Язык',
    'zapretUpdates': 'Обновления Zapret',
    'appUpdates': 'Обновления приложения',
    'pathToZapret': 'Путь к Zapret',
    'github': 'GitHub · Zapret',
    'pathUpdated': 'Путь обновлён',
    'msgBusy': 'Уже выполняется…',
    'msgLaunch': 'Запуск',
    'msgStop': 'Остановка: winws.exe завершён',
    'msgAutostartSet': 'Автозапуск установлен',
    'msgAutostartRemoved': 'Автозапуск удалён',
    'msgNoConfigs': 'Нет конфигов для автозапуска',
    'msgIpsetUpdated': 'IPSet: список обновлён',
    'msgIpsetHttp': 'IPSet: ошибка HTTP',
    'msgIpsetError': 'IPSet: ошибка',
    'msgAlready': 'Уже в режиме',
    'msgUnknown': 'Неизвестный режим',
    'msgApplies': 'Применится после перезапуска zapret',
    'msgLatestZ2': 'Последняя версия Z2',
    'msgHttp': 'Ошибка HTTP',
    'msgError': 'Ошибка',
    'msgNoZip': 'В релизе нет .zip',
    'msgUnpack': 'Ошибка распаковки',
    'msgSearch': 'Поиск релиза…',
    'msgDownloading': 'Скачивание',
    'msgInstalling': 'Установка…',
    'msgInstalled': 'Скачан и установлен',
    'msgDownloadError': 'Ошибка скачивания',
    'msgEmpty': 'Пустой ответ сервера',
    'msgExtracting': 'Распаковка…',
    'otaLatest': 'Уже установлена последняя версия',
    'otaRestart': 'Перезапуск…',
    'updateAvailable': 'Доступна новая версия',
    'installUpdate': 'Установить',
    'cancel': 'Отмена',
    'currentVersion': 'Текущая версия',
    'installingUpdate': 'Установка обновления…',
    'mode_disabled': 'Отключён',
    'mode_all': 'TCP + UDP',
    'mode_tcp': 'TCP',
    'mode_udp': 'UDP',
    'mode_loaded': 'Загружен',
    'mode_none': 'Нет',
    'mode_any': 'Любой',
    'downloadZapret': 'Скачать Zapret',
    'removeService': 'Удалить сервис',
    'removeServiceTitle': 'Удалить сервис zapret?',
    'removeServiceBody':
        'Обход будет остановлен, службы zapret и WinDivert будут удалены.',
    'remove': 'Удалить',
    'msgServiceRemoved': 'Сервис zapret удалён',
    'footer': 'Сделано с ❤️ для свободного интернета',
    'notification': 'Уведомление',
  };

  static const Map<String, String> _en = {
    'navHome': 'Home',
    'navSettings': 'Settings',
    'configuration': 'Configuration',
    'tooltipIpset': 'Update IPSet list',
    'noConfigsPath': 'No configs found — set the path in settings',
    'noConfigs': 'No configs found',
    'start': 'Start',
    'stop': 'Stop',
    'restart': 'Restart',
    'gameFilter': 'Game Filter',
    'ipsetFilter': 'IPSet Filter',
    'darkTheme': 'Dark theme',
    'launchWindows': 'Launch with Windows',
    'zapretAutostart': 'Zapret autostart',
    'language': 'Language',
    'zapretUpdates': 'Zapret updates',
    'appUpdates': 'App updates',
    'pathToZapret': 'Path to Zapret',
    'github': 'GitHub · Zapret',
    'pathUpdated': 'Path updated',
    'msgBusy': 'Already running…',
    'msgLaunch': 'Launch',
    'msgStop': 'Stop: winws.exe terminated',
    'msgAutostartSet': 'Autostart installed',
    'msgAutostartRemoved': 'Autostart removed',
    'msgNoConfigs': 'No configs for autostart',
    'msgIpsetUpdated': 'IPSet: list updated',
    'msgIpsetHttp': 'IPSet: HTTP error',
    'msgIpsetError': 'IPSet: error',
    'msgAlready': 'Already in mode',
    'msgUnknown': 'Unknown mode',
    'msgApplies': 'Applies after zapret restart',
    'msgLatestZ2': 'Latest Z2 version',
    'msgHttp': 'HTTP error',
    'msgError': 'Error',
    'msgNoZip': 'No .zip in release',
    'msgUnpack': 'Unpack error',
    'msgSearch': 'Searching release…',
    'msgDownloading': 'Downloading',
    'msgInstalling': 'Installing…',
    'msgInstalled': 'Downloaded and installed',
    'msgDownloadError': 'Download error',
    'msgEmpty': 'Empty server response',
    'msgExtracting': 'Extracting…',
    'otaLatest': 'Already up to date',
    'otaRestart': 'Restarting…',
    'updateAvailable': 'New version available',
    'installUpdate': 'Install',
    'cancel': 'Cancel',
    'currentVersion': 'Current version',
    'installingUpdate': 'Installing update…',
    'mode_disabled': 'Disabled',
    'mode_all': 'TCP + UDP',
    'mode_tcp': 'TCP',
    'mode_udp': 'UDP',
    'mode_loaded': 'Loaded',
    'mode_none': 'None',
    'mode_any': 'Any',
    'downloadZapret': 'Download Zapret',
    'removeService': 'Remove service',
    'removeServiceTitle': 'Remove zapret service?',
    'removeServiceBody':
        'The bypass will be stopped and the zapret / WinDivert services will be removed.',
    'remove': 'Remove',
    'msgServiceRemoved': 'Zapret service removed',
    'footer': 'Made with ❤️ for free internet',
    'notification': 'Notification',
  };

  static const Map<String, String> _es = {
    'navHome': 'Inicio',
    'navSettings': 'Ajustes',
    'configuration': 'Configuración',
    'tooltipIpset': 'Actualizar lista IPSet',
    'noConfigsPath': 'No hay configs — establece la ruta en ajustes',
    'noConfigs': 'No hay configs',
    'start': 'Iniciar',
    'stop': 'Detener',
    'restart': 'Reiniciar',
    'gameFilter': 'Filtro de juego',
    'ipsetFilter': 'Filtro IPSet',
    'darkTheme': 'Tema oscuro',
    'launchWindows': 'Iniciar con Windows',
    'zapretAutostart': 'Autoinicio de Zapret',
    'language': 'Idioma',
    'zapretUpdates': 'Actualizaciones de Zapret',
    'appUpdates': 'Actualizaciones de la app',
    'pathToZapret': 'Ruta a Zapret',
    'github': 'GitHub · Zapret',
    'pathUpdated': 'Ruta actualizada',
    'msgBusy': 'Ya en ejecución…',
    'msgLaunch': 'Inicio',
    'msgStop': 'Detenido: winws.exe terminado',
    'msgAutostartSet': 'Autoinicio instalado',
    'msgAutostartRemoved': 'Autoinicio eliminado',
    'msgNoConfigs': 'No hay configs para autoinicio',
    'msgIpsetUpdated': 'IPSet: lista actualizada',
    'msgIpsetHttp': 'IPSet: error HTTP',
    'msgIpsetError': 'IPSet: error',
    'msgAlready': 'Ya en modo',
    'msgUnknown': 'Modo desconocido',
    'msgApplies': 'Se aplica tras reiniciar zapret',
    'msgLatestZ2': 'Última versión de Z2',
    'msgHttp': 'Error HTTP',
    'msgError': 'Error',
    'msgNoZip': 'No hay .zip en el release',
    'msgUnpack': 'Error de descompresión',
    'msgSearch': 'Buscando release…',
    'msgDownloading': 'Descargando',
    'msgInstalling': 'Instalando…',
    'msgInstalled': 'Descargado e instalado',
    'msgDownloadError': 'Error de descarga',
    'msgEmpty': 'Respuesta vacía del servidor',
    'msgExtracting': 'Extrayendo…',
    'otaLatest': 'Ya estás actualizado',
    'otaRestart': 'Reiniciando…',
    'updateAvailable': 'Nueva versión disponible',
    'installUpdate': 'Instalar',
    'cancel': 'Cancelar',
    'currentVersion': 'Versión actual',
    'installingUpdate': 'Instalando actualización…',
    'mode_disabled': 'Desactivado',
    'mode_all': 'TCP + UDP',
    'mode_tcp': 'TCP',
    'mode_udp': 'UDP',
    'mode_loaded': 'Cargado',
    'mode_none': 'Ninguno',
    'mode_any': 'Cualquiera',
    'downloadZapret': 'Descargar Zapret',
    'removeService': 'Eliminar servicio',
    'removeServiceTitle': '¿Eliminar servicio zapret?',
    'removeServiceBody':
        'El bypass se detendrá y los servicios zapret y WinDivert se eliminarán.',
    'remove': 'Eliminar',
    'msgServiceRemoved': 'Servicio zapret eliminado',
    'footer': 'Hecho con ❤️ para un internet libre',
    'notification': 'Notificación',
  };

  static const Map<String, String> _de = {
    'navHome': 'Start',
    'navSettings': 'Einstellungen',
    'configuration': 'Konfiguration',
    'tooltipIpset': 'IPSet-Liste aktualisieren',
    'noConfigsPath': 'Keine Configs — Pfad in Einstellungen setzen',
    'noConfigs': 'Keine Configs',
    'start': 'Starten',
    'stop': 'Stoppen',
    'restart': 'Neustarten',
    'gameFilter': 'Spiel-Filter',
    'ipsetFilter': 'IPSet-Filter',
    'darkTheme': 'Dunkles Theme',
    'launchWindows': 'Mit Windows starten',
    'zapretAutostart': 'Zapret-Autostart',
    'language': 'Sprache',
    'zapretUpdates': 'Zapret-Updates',
    'appUpdates': 'App-Updates',
    'pathToZapret': 'Pfad zu Zapret',
    'github': 'GitHub · Zapret',
    'pathUpdated': 'Pfad aktualisiert',
    'msgBusy': 'Läuft bereits…',
    'msgLaunch': 'Start',
    'msgStop': 'Gestoppt: winws.exe beendet',
    'msgAutostartSet': 'Autostart eingerichtet',
    'msgAutostartRemoved': 'Autostart entfernt',
    'msgNoConfigs': 'Keine Configs für Autostart',
    'msgIpsetUpdated': 'IPSet: Liste aktualisiert',
    'msgIpsetHttp': 'IPSet: HTTP-Fehler',
    'msgIpsetError': 'IPSet: Fehler',
    'msgAlready': 'Bereits im Modus',
    'msgUnknown': 'Unbekannter Modus',
    'msgApplies': 'Wirkt nach Zapret-Neustart',
    'msgLatestZ2': 'Neueste Z2-Version',
    'msgHttp': 'HTTP-Fehler',
    'msgError': 'Fehler',
    'msgNoZip': 'Kein .zip im Release',
    'msgUnpack': 'Entpackfehler',
    'msgSearch': 'Suche Release…',
    'msgDownloading': 'Wird heruntergeladen',
    'msgInstalling': 'Wird installiert…',
    'msgInstalled': 'Heruntergeladen und installiert',
    'msgDownloadError': 'Download-Fehler',
    'msgEmpty': 'Leere Serverantwort',
    'msgExtracting': 'Wird entpackt…',
    'otaLatest': 'Bereits aktuell',
    'otaRestart': 'Neustart…',
    'updateAvailable': 'Neue Version verfügbar',
    'installUpdate': 'Installieren',
    'cancel': 'Abbrechen',
    'currentVersion': 'Aktuelle Version',
    'installingUpdate': 'Update wird installiert…',
    'mode_disabled': 'Deaktiviert',
    'mode_all': 'TCP + UDP',
    'mode_tcp': 'TCP',
    'mode_udp': 'UDP',
    'mode_loaded': 'Geladen',
    'mode_none': 'Keine',
    'mode_any': 'Beliebig',
    'downloadZapret': 'Zapret herunterladen',
    'removeService': 'Dienst entfernen',
    'removeServiceTitle': 'Zapret-Dienst entfernen?',
    'removeServiceBody':
        'Der Bypass wird gestoppt, zapret- und WinDivert-Dienste werden entfernt.',
    'remove': 'Entfernen',
    'msgServiceRemoved': 'Zapret-Dienst entfernt',
    'footer': 'Mit ❤️ für ein freies Internet',
    'notification': 'Benachrichtigung',
  };
}